### ISSUE TITLE
Can't manage to require de svg file and test the library

### ISSUE THREAD

**Issue by Richacinas** [blunt1337/pixi-svg-loader#1]
Hello there!

I have a simple code that I wrote in order to test your library, but I can't get it to work. I installed through npm on my project, then I run:

`var OttoStage = require('pixi-svg!../../../app/public/static/image/otto.svg');
    self.stage = new OttoStage();`

And all I get is this error:

> Uncaught Error: Cannot find module "pixi-svg!../../../app/public/static/image/otto.svg"

**Comment by Richacinas** [comment]
I'm using:

> "webpack": "^1.13.3"

**Comment by blunt1337** [comment]
Hi!
Did you tried with 'pixi-svg-loader' instead of 'pixi-svg'?

**Comment by Richacinas** [comment]
yes. This happened using pixi-svg-loader

**Comment by blunt1337** [comment]
Did you do "npm i -D pixi-svg-loader" then require('pixi-svg-loader!....') ?
