### ISSUE TITLE
No event triggered

### ISSUE THREAD

**Issue by mrdev023** [blunt1337/pixi-svg-loader#4]
Code used : First Sample of your project

```javascript
var Origin = require('../../index.js?default_origin=cc!svgo-loader!./origin.svg');

// Instanciate
var origin = new Origin();
origin.sun.interactive = true;
origin.sun.on('mousedown', () => { console.log('yay') } );
```

**Comment by blunt1337** [comment]
You need to use "pointerdown" event, and you can add "buttonMode = true" too.
See pixi basic sample: https://pixijs.io/examples/#/basics/click.js

PS: this is a PIXI problem, not my loader.
